const { GoogleGenAI } = require("@google/genai");
const { GEMINI_API_KEY, GEMINI_MODEL } = require("../../secrets.js");

/**
 * Lazy-initialized Gemini client — same pattern used in message-controller.js.
 * Returns null if GEMINI_API_KEY is not configured.
 */
let ai;
const getGeminiClient = () => {
  if (!GEMINI_API_KEY) return null;
  if (!ai) ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  return ai;
};

/**
 * Builds the structured prompt for Gemini.
 * The model is instructed to return ONLY a JSON object — no markdown fences.
 */
function buildLegalPrompt(query, jurisdiction) {
  return `You are a knowledgeable legal information assistant. A user has described a legal situation.
Your task is to analyze it and return a structured JSON response (no markdown, no code fences — raw JSON only).

User Query: """${query}"""
Jurisdiction: ${jurisdiction}

Return ONLY a valid JSON object with these exact keys:
{
  "caseType": "<short label for the type of legal case, e.g. 'Employment Dispute', 'Property Dispute', 'Consumer Complaint'>",
  "legalDomain": "<area of law, e.g. 'Labour Law', 'Civil Law', 'Criminal Law', 'Family Law', 'Consumer Law'>",
  "caseSummary": "<2–3 sentence neutral summary of the situation as presented>",
  "advisoryResponse": "<structured advisory with exactly these five sections, each separated by a blank line:

ISSUE IDENTIFIED:
[Describe the core legal issue in plain language]

GENERAL LEGAL CONTEXT:
[Explain the relevant laws, rights, or legal principles that may apply in ${jurisdiction}]

POSSIBLE NEXT STEPS:
[List 3–5 actionable steps the user can consider, numbered]

DOCUMENTS/INFORMATION THE USER SHOULD GATHER:
[List relevant documents or evidence they should collect, bulleted]

IMPORTANT DISCLAIMER:
This information is generated by AI for general informational purposes only and does not constitute professional legal advice. Laws and procedures vary and change over time. You should consult a qualified lawyer licensed in your jurisdiction before taking any legal action.>"
}

Do not include any text outside the JSON object. Do not add markdown fences. Return only the raw JSON.`;
}

/**
 * Calls Gemini with the legal advisory prompt and returns parsed structured data.
 * Throws on network/API errors so the controller can handle status updates.
 *
 * @param {string} query     - The user's legal question
 * @param {string} jurisdiction - The jurisdiction, e.g. "India"
 * @returns {{ caseType, legalDomain, caseSummary, advisoryResponse }}
 */
async function generateAdvisory(query, jurisdiction = "India") {
  const geminiClient = getGeminiClient();
  if (!geminiClient) {
    throw new Error("Gemini API key is not configured. Cannot generate legal advisory.");
  }

  const prompt = buildLegalPrompt(query, jurisdiction);

  const response = await geminiClient.models.generateContent({
    model: GEMINI_MODEL,
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    config: {
      temperature: 0.4,
      maxOutputTokens: 2048,
    },
  });

  // Extract text from response
  const rawText = response?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";

  if (!rawText) {
    throw new Error("Empty response received from Gemini.");
  }

  // Strip any accidental markdown fences before parsing
  const cleaned = rawText
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    // If JSON parsing fails, return a best-effort fallback using raw text
    console.error("[legalAdvisoryService] Failed to parse Gemini JSON:", cleaned.slice(0, 300));
    throw new Error("Failed to parse structured response from AI. Please try again.");
  }

  const { caseType = "", legalDomain = "", caseSummary = "", advisoryResponse = "" } = parsed;

  return { caseType, legalDomain, caseSummary, advisoryResponse };
}

module.exports = { generateAdvisory };
