const { GoogleGenAI } = require("@google/genai");
const { GEMINI_API_KEY, GEMINI_MODEL } = require("../../secrets.js");

/**
 * Lazy-initialized Gemini client — same pattern used across the app.
 */
let ai;
const getGeminiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY || GEMINI_API_KEY;
  if (!apiKey) return null;
  if (!ai) ai = new GoogleGenAI({ apiKey });
  return ai;
};

/**
 * Builds the prompt for the Legal Response / Drafter Agent.
 *
 * @param {string} query
 * @param {object} intake
 * @param {Array<object>} retrievedSources
 * @param {Array<object>} precedents
 * @returns {string}
 */
function buildDrafterPrompt(query, intake, retrievedSources = [], precedents = []) {
  const {
    caseType,
    legalDomain,
    summary,
    relevantEntities,
    jurisdiction,
    keywords,
  } = intake;

  const entitiesStr = relevantEntities && relevantEntities.length ? relevantEntities.join(", ") : "N/A";
  const keywordsStr = keywords && keywords.length ? keywords.join(", ") : "N/A";

  let sourcesBlock = "";
  if (retrievedSources && retrievedSources.length > 0) {
    const formatted = retrievedSources
      .map(
        (src, idx) =>
          `[SOURCE ${idx + 1}]: "${src.title}" (${src.source})\nURL: ${
            src.sourceUrl || "N/A"
          }\nDOMAIN: ${src.legalDomain}\nEXCERPT:\n${src.content}`
      )
      .join("\n\n---\n\n");
    sourcesBlock = `--- RETRIEVED VERIFIED LEGAL SOURCES ---\nThe following verified legal excerpts were retrieved from the knowledge base for this issue:\n\n${formatted}\n--- END SOURCES ---\n`;
  } else {
    sourcesBlock = `--- RETRIEVED VERIFIED LEGAL SOURCES ---\nNo specific legal documents were retrieved from the knowledge base for this query.\n--- END SOURCES ---\n`;
  }

  let precedentsBlock = "";
  if (precedents && precedents.length > 0) {
    const formattedP = precedents
      .map(
        (p, idx) =>
          `[PRECEDENT ${idx + 1}]: "${p.caseName}" (${p.court}, ${p.dateOrYear})\nRELEVANCE: ${p.relevanceExplanation}\nSUMMARY: ${p.summary}`
      )
      .join("\n\n---\n\n");
    precedentsBlock = `--- RETRIEVED VERIFIED LEGAL PRECEDENTS ---\nThe following verified court judgments were retrieved for this issue:\n\n${formattedP}\n--- END PRECEDENTS ---\n`;
  } else {
    precedentsBlock = `--- RETRIEVED VERIFIED LEGAL PRECEDENTS ---\nNo reliable related legal precedents were identified for this query.\n--- END PRECEDENTS ---\n`;
  }

  return `You are a professional legal information specialist and drafting agent.
Your task is to analyze the user's issue, intake summary, verified legal sources, and verified precedents to produce a structured, clear, and realistic legal advisory.

--- CASE INTAKE SUMMARY ---
User Query: """${query}"""
Jurisdiction: ${jurisdiction}
Case Type: ${caseType}
Legal Domain: ${legalDomain}
Situation Summary: ${summary}
Relevant Entities: ${entitiesStr}
Keywords: ${keywordsStr}
--- END INTAKE ---

${sourcesBlock}
${precedentsBlock}

OPERATIONAL CONSTRAINTS & ACCURACY RULES:
1. PRIORITIZE RETRIEVED SOURCES & PRECEDENTS: Ground your legal explanation in the provided sources and court precedents.
2. NO FABRICATED CASE LAWS: NEVER invent, hallucinate, or fabricate any court judgment names, citations, section numbers, or source URLs not provided above.
3. EXPLICIT UNCERTAINTY: If key details or precedents are absent, explicitly highlight limitations and uncertainty in the "limitationsAndUncertainty" section.
4. NO ATTORNEY CLAIMS: Never state or imply that you are a licensed attorney, and never offer definitive legal guarantees or court outcome predictions.
5. NO LEGAL CHOICE MANDATE: Frame next steps as informational options for the user to discuss with a qualified legal professional.

Return ONLY a raw JSON object (no markdown fences, no text outside JSON) matching this exact schema:

{
  "issueIdentified": "<2-4 sentences describing the core legal issue in plain language, referencing the classified case type and relevant entities>",
  "generalLegalContext": "<3-5 sentences explaining relevant legal principles, statutes, and rights in ${jurisdiction} under ${legalDomain}. Explicitly cite retrieved sources where applicable.>",
  "relevantLegalInformation": [
    {
      "title": "<title of retrieved source or law>",
      "source": "<source name/statute>",
      "sourceUrl": "<source URL or empty string>",
      "excerpt": "<concise summary of key relevant rule>",
      "legalDomain": "${legalDomain}"
    }
  ],
  "possibleNextSteps": [
    "1. <actionable step 1>",
    "2. <actionable step 2>",
    "3. <actionable step 3>"
  ],
  "documentsToGather": [
    "<document or piece of evidence 1>",
    "<document or piece of evidence 2>",
    "<document or piece of evidence 3>"
  ],
  "limitationsAndUncertainty": "<2-3 sentences explaining any missing information, factual uncertainties, or nuances requiring professional legal review>",
  "disclaimer": "This information is generated by AI for general informational purposes only and does not constitute professional legal advice. Laws and procedures vary by jurisdiction and change over time. You should consult a qualified lawyer licensed in ${jurisdiction} before taking any legal action."
}

Note for "relevantLegalInformation": Include items ONLY if retrieved sources were provided above. If no retrieved sources were provided, return an empty array [] for "relevantLegalInformation".

Return ONLY the raw JSON object.`;
}

/**
 * Parses Gemini's JSON response cleanly.
 *
 * @param {string} raw
 * @returns {object}
 */
function parseDrafterResponse(raw) {
  let cleaned = (raw || "").trim();
  cleaned = cleaned.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();

  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    cleaned = jsonMatch[0].trim();
  }

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.error("[LegalDrafterAgent] Failed to parse JSON response:", err.message);
    if (process.env.NODE_ENV !== "production") {
      console.error("[LegalDrafterAgent] Raw output:", raw);
    }
    throw new Error("Unable to process your legal advisory right now. Please try again.");
  }
}

/**
 * Runs the Legal Response / Drafter Agent.
 *
 * @param {string} query
 * @param {object} intake
 * @param {Array<object>} retrievedSources
 * @param {Array<object>} precedents
 * @returns {Promise<{
 *   issueIdentified: string,
 *   generalLegalContext: string,
 *   relevantLegalInformation: Array<object>,
 *   possibleNextSteps: string[],
 *   documentsToGather: string[],
 *   limitationsAndUncertainty: string,
 *   disclaimer: string
 * }>}
 */
async function runDrafter(query, intake, retrievedSources = [], precedents = []) {
  const client = getGeminiClient();
  if (!client) {
    throw new Error("Gemini API key is not configured. Cannot run Legal Drafter Agent.");
  }

  const prompt = buildDrafterPrompt(query, intake, retrievedSources, precedents);

  console.log("[LegalDrafterAgent] Calling Gemini with responseMimeType: application/json...");

  const response = await client.models.generateContent({
    model: GEMINI_MODEL,
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    config: {
      responseMimeType: "application/json",
      temperature: 0.3,
      maxOutputTokens: 2048,
    },
  });

  const rawText = response?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  if (!rawText) {
    throw new Error("Legal Drafter Agent received an empty response from Gemini.");
  }

  const parsed = parseDrafterResponse(rawText);

  // Normalize shape with safe fallbacks
  return {
    issueIdentified: typeof parsed.issueIdentified === "string" ? parsed.issueIdentified.trim() : "",
    generalLegalContext: typeof parsed.generalLegalContext === "string" ? parsed.generalLegalContext.trim() : "",
    relevantLegalInformation: Array.isArray(parsed.relevantLegalInformation) ? parsed.relevantLegalInformation : [],
    possibleNextSteps: Array.isArray(parsed.possibleNextSteps) ? parsed.possibleNextSteps.filter(Boolean).map(String) : [],
    documentsToGather: Array.isArray(parsed.documentsToGather) ? parsed.documentsToGather.filter(Boolean).map(String) : [],
    limitationsAndUncertainty: typeof parsed.limitationsAndUncertainty === "string" ? parsed.limitationsAndUncertainty.trim() : "",
    disclaimer: typeof parsed.disclaimer === "string" ? parsed.disclaimer.trim() : "This information is generated by AI for general informational purposes only and does not constitute professional legal advice.",
  };
}

module.exports = { runDrafter };
