const { GoogleGenAI } = require("@google/genai");
const { GEMINI_API_KEY, GEMINI_MODEL } = require("../../secrets.js");

/**
 * Lazy-initialized Gemini client — same pattern used across the app.
 */
let ai;
const getGeminiClient = () => {
  if (!GEMINI_API_KEY) return null;
  if (!ai) ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  return ai;
};

/**
 * Builds the prompt for the Legal Response / Drafter Agent.
 *
 * @param {string} query
 * @param {object} intake
 * @param {Array<object>} retrievedSources
 * @returns {string}
 */
function buildDrafterPrompt(query, intake, retrievedSources = []) {
  const {
    caseType,
    legalDomain,
    summary,
    relevantEntities,
    jurisdiction,
    keywords,
  } = intake;

  const entitiesStr = relevantEntities && relevantEntities.length ? relevantEntities.join(", ") : "N/A";
  const keywordsStr = keywords && keywords.length ? keywords.join(", ") : "N/A";

  let sourcesBlock = "";
  if (retrievedSources && retrievedSources.length > 0) {
    const formatted = retrievedSources
      .map(
        (src, idx) =>
          `[SOURCE ${idx + 1}]: "${src.title}" (${src.source})\nURL: ${
            src.sourceUrl || "N/A"
          }\nDOMAIN: ${src.legalDomain}\nEXCERPT:\n${src.content}`
      )
      .join("\n\n---\n\n");
    sourcesBlock = `--- RETRIEVED VERIFIED LEGAL SOURCES ---\nThe following verified legal excerpts were retrieved from the knowledge base for this issue:\n\n${formatted}\n--- END SOURCES ---\n`;
  } else {
    sourcesBlock = `--- RETRIEVED VERIFIED LEGAL SOURCES ---\nNo specific legal documents were retrieved from the knowledge base for this query.\n--- END SOURCES ---\n`;
  }

  return `You are a professional legal information specialist and drafting agent.
Your task is to analyze the user's issue, intake summary, and verified retrieved legal sources to produce a structured, clear, and realistic legal information response.

--- CASE INTAKE SUMMARY ---
User Query: """${query}"""
Jurisdiction: ${jurisdiction}
Case Type: ${caseType}
Legal Domain: ${legalDomain}
Situation Summary: ${summary}
Relevant Entities: ${entitiesStr}
Keywords: ${keywordsStr}
--- END INTAKE ---

${sourcesBlock}

OPERATIONAL CONSTRAINTS & ACCURACY RULES:
1. PRIORITIZE RETRIEVED SOURCES: When retrieved sources are provided, ground your explanation of laws, sections, and procedures directly in those sources.
2. NO FABRICATIONS: NEVER invent, hallucinate, or fabricate any statute names, section numbers, or source URLs that do not exist or are not provided in the retrieved sources.
3. EXPLICIT UNCERTAINTY: If key details are missing from the query or retrieved sources, explicitly highlight limitations and uncertainty in the "limitationsAndUncertainty" section.
4. NO ATTORNEY CLAIMS: Never state or imply that you are a licensed attorney, and never offer definitive legal guarantees or court outcome predictions.
5. NO LEGAL CHOICE MANDATE: Frame next steps as informational options for the user to discuss with a qualified legal professional.

Return ONLY a raw JSON object (no markdown fences, no text outside JSON) matching this exact schema:

{
  "issueIdentified": "<2-4 sentences describing the core legal issue in plain language, referencing the classified case type and relevant entities>",
  "generalLegalContext": "<3-5 sentences explaining relevant legal principles, statutes, and rights in ${jurisdiction} under ${legalDomain}. Explicitly cite retrieved sources where applicable.>",
  "relevantLegalInformation": [
    {
      "title": "<title of retrieved source or law>",
      "source": "<source name/statute>",
      "sourceUrl": "<source URL or empty string>",
      "excerpt": "<concise summary of key relevant rule>",
      "legalDomain": "${legalDomain}"
    }
  ],
  "possibleNextSteps": [
    "1. <actionable step 1>",
    "2. <actionable step 2>",
    "3. <actionable step 3>"
  ],
  "documentsToGather": [
    "<document or piece of evidence 1>",
    "<document or piece of evidence 2>",
    "<document or piece of evidence 3>"
  ],
  "limitationsAndUncertainty": "<2-3 sentences explaining any missing information, factual uncertainties, or nuances requiring professional legal review>",
  "disclaimer": "This information is generated by AI for general informational purposes only and does not constitute professional legal advice. Laws and procedures vary by jurisdiction and change over time. You should consult a qualified lawyer licensed in ${jurisdiction} before taking any legal action."
}

Note for "relevantLegalInformation": Include items ONLY if retrieved sources were provided above. If no retrieved sources were provided, return an empty array [] for "relevantLegalInformation".

Return ONLY the raw JSON object.`;
}

/**
 * Parses Gemini's JSON response cleanly.
 *
 * @param {string} raw
 * @returns {object}
 */
function parseDrafterResponse(raw) {
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.error("[legalDrafterAgent] Failed to parse JSON response:", cleaned.slice(0, 400));
    throw new Error("Legal Drafter Agent produced invalid JSON output. Please try again.");
  }
}

/**
 * Runs the Legal Response / Drafter Agent.
 *
 * @param {string} query
 * @param {object} intake
 * @param {Array<object>} retrievedSources
 * @returns {Promise<{
 *   issueIdentified: string,
 *   generalLegalContext: string,
 *   relevantLegalInformation: Array<object>,
 *   possibleNextSteps: string[],
 *   documentsToGather: string[],
 *   limitationsAndUncertainty: string,
 *   disclaimer: string
 * }>}
 */
async function runDrafter(query, intake, retrievedSources = []) {
  const client = getGeminiClient();
  if (!client) {
    throw new Error("Gemini API key is not configured. Cannot run Legal Drafter Agent.");
  }

  const prompt = buildDrafterPrompt(query, intake, retrievedSources);

  const response = await client.models.generateContent({
    model: GEMINI_MODEL,
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    config: {
      temperature: 0.3,
      maxOutputTokens: 2048,
    },
  });

  const rawText = response?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  if (!rawText) {
    throw new Error("Legal Drafter Agent received an empty response from Gemini.");
  }

  const parsed = parseDrafterResponse(rawText);

  // Normalize shape with safe fallbacks
  return {
    issueIdentified: typeof parsed.issueIdentified === "string" ? parsed.issueIdentified.trim() : "",
    generalLegalContext: typeof parsed.generalLegalContext === "string" ? parsed.generalLegalContext.trim() : "",
    relevantLegalInformation: Array.isArray(parsed.relevantLegalInformation) ? parsed.relevantLegalInformation : [],
    possibleNextSteps: Array.isArray(parsed.possibleNextSteps) ? parsed.possibleNextSteps.filter(Boolean).map(String) : [],
    documentsToGather: Array.isArray(parsed.documentsToGather) ? parsed.documentsToGather.filter(Boolean).map(String) : [],
    limitationsAndUncertainty: typeof parsed.limitationsAndUncertainty === "string" ? parsed.limitationsAndUncertainty.trim() : "",
    disclaimer: typeof parsed.disclaimer === "string" ? parsed.disclaimer.trim() : "This information is generated by AI for general informational purposes only and does not constitute professional legal advice.",
  };
}

module.exports = { runDrafter };
