const { GoogleGenAI } = require("@google/genai");
const { GEMINI_API_KEY, GEMINI_MODEL } = require("../../secrets.js");
const { runIntake } = require("./caseIntakeAgent.js");

/**
 * Lazy-initialized Gemini client — same pattern used in message-controller.js.
 * Returns null if GEMINI_API_KEY is not configured.
 */
let ai;
const getGeminiClient = () => {
  if (!GEMINI_API_KEY) return null;
  if (!ai) ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  return ai;
};

/**
 * Builds the Stage 2 advisory prompt using enriched intake data from the
 * Case Intake Agent. The model now receives pre-classified context so it can
 * focus on producing a high-quality advisory rather than re-doing classification.
 *
 * @param {string} query
 * @param {object} intake  — structured output from caseIntakeAgent.runIntake()
 * @returns {string}
 */
function buildAdvisoryPrompt(query, intake) {
  const {
    caseType,
    legalDomain,
    summary,
    relevantEntities,
    jurisdiction,
    keywords,
  } = intake;

  const entitiesStr  = relevantEntities.length ? relevantEntities.join(", ") : "N/A";
  const keywordsStr  = keywords.length         ? keywords.join(", ")         : "N/A";

  return `You are a knowledgeable legal information assistant. A legal case intake has already been completed for this user's issue. Use the pre-classified intake data to produce a thorough, well-structured advisory.

--- INTAKE SUMMARY ---
Original Query: """${query}"""
Jurisdiction: ${jurisdiction}
Case Type: ${caseType}
Legal Domain: ${legalDomain}
Situation Summary: ${summary}
Relevant Entities: ${entitiesStr}
Key Legal Terms: ${keywordsStr}
--- END INTAKE ---

Using this context, return ONLY a raw JSON object (no markdown, no code fences) with exactly these keys:

{
  "caseType": "${caseType}",
  "legalDomain": "${legalDomain}",
  "caseSummary": "<2–3 sentence neutral summary of the situation>",
  "advisoryResponse": "<structured advisory with exactly these five labelled sections, each separated by a blank line:

ISSUE IDENTIFIED:
[Describe the core legal issue in plain language, referencing the classified case type and entities]

GENERAL LEGAL CONTEXT:
[Explain the relevant laws, statutes, rights, or legal principles that apply in ${jurisdiction} for a ${caseType} under ${legalDomain}]

POSSIBLE NEXT STEPS:
[List 3–5 numbered actionable steps the user can take]

DOCUMENTS/INFORMATION THE USER SHOULD GATHER:
[Bulleted list of evidence and documents relevant to a ${caseType}]

IMPORTANT DISCLAIMER:
This information is generated by AI for general informational purposes only and does not constitute professional legal advice. Laws and procedures vary and change over time. You should consult a qualified lawyer licensed in ${jurisdiction} before taking any legal action.>"
}

Return ONLY the JSON object. Do not add any text, explanation, or markdown outside it.`;
}

/**
 * Parses Gemini's JSON response, stripping any accidental markdown fences.
 *
 * @param {string} raw
 * @returns {object}
 */
function parseAdvisoryResponse(raw) {
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch {
    console.error("[legalAdvisoryService] Failed to parse advisory JSON:", cleaned.slice(0, 300));
    throw new Error("Failed to parse structured advisory response from AI. Please try again.");
  }
}

/**
 * Two-stage Legal Advisory orchestrator.
 *
 * Stage 1 — Case Intake Agent (caseIntakeAgent.js):
 *   Classifies the issue, extracts entities & keywords, writes a neutral summary.
 *   Does NOT produce any legal answer.
 *
 * Stage 2 — Advisory Generator (this file):
 *   Receives the enriched intake data and generates a full, contextualised
 *   advisory response using a targeted Gemini prompt.
 *
 * @param {string} query
 * @param {string} jurisdiction
 * @returns {Promise<{
 *   caseType: string,
 *   legalDomain: string,
 *   caseSummary: string,
 *   advisoryResponse: string,
 *   relevantEntities: string[],
 *   keywords: string[]
 * }>}
 */
async function generateAdvisory(query, jurisdiction = "India") {
  const geminiClient = getGeminiClient();
  if (!geminiClient) {
    throw new Error("Gemini API key is not configured. Cannot generate legal advisory.");
  }

  // ── Stage 1: Case Intake ──────────────────────────────────────────────────
  console.log("[legalAdvisoryService] Stage 1 — Running Case Intake Agent…");
  const intake = await runIntake(query, jurisdiction);
  console.log("[legalAdvisoryService] Intake complete:", {
    caseType:    intake.caseType,
    legalDomain: intake.legalDomain,
    keywords:    intake.keywords,
  });

  // ── Stage 2: Advisory Generation (with enriched context) ─────────────────
  console.log("[legalAdvisoryService] Stage 2 — Generating advisory using intake data…");
  const advisoryPrompt = buildAdvisoryPrompt(query, intake);

  const response = await geminiClient.models.generateContent({
    model: GEMINI_MODEL,
    contents: [{ role: "user", parts: [{ text: advisoryPrompt }] }],
    config: {
      temperature: 0.4,
      maxOutputTokens: 2048,
    },
  });

  const rawText = response?.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  if (!rawText) {
    throw new Error("Advisory generator received an empty response from Gemini.");
  }

  const parsed = parseAdvisoryResponse(rawText);

  return {
    // Advisory fields — use intake values as authoritative fallback for classification
    caseType:         parsed.caseType        || intake.caseType,
    legalDomain:      parsed.legalDomain     || intake.legalDomain,
    caseSummary:      parsed.caseSummary     || intake.summary,
    advisoryResponse: parsed.advisoryResponse || "",
    // Pass intake enrichment through for storage
    relevantEntities: intake.relevantEntities,
    keywords:         intake.keywords,
  };
}

module.exports = { generateAdvisory };
